import causes, effects


def check(self, path):
    self.assertState(
        'GET/POST',
        path,
        [
            causes.person_not_logged_in,
            causes.valid_domain,
        ],
        [
            effects.redirected('/person/login/'),
        ]
    )
    self.assertState(
        'GET/POST',
        path,
        [
            causes.owner_logged_in,
            causes.mismatched_domain,
        ],
        [
            effects.redirected('/person/login/'),
        ]
    )
    self.assertState(
        'GET/POST',
        path,
        [
            causes.person_not_logged_in,
            causes.invalid_domain,
        ],
        [
            effects.status(404),
        ]
    )
    self.assertState(
        'GET/POST',
        path,
        [
            causes.person_logged_in,
            causes.invalid_domain,
        ],
        [
            effects.status(404),
        ]
    )
    self.assertState(
        'GET/POST',
        path,
        [
            causes.person_not_logged_in,
            causes.invalid_domain,
        ],
        [
            effects.status(404),
        ]
    )
    self.assertState(
        'GET/POST',
        path,
        [
            causes.person_logged_in,
            causes.valid_domain,
        ],
        [
            effects.status(403),
        ]
    )
    
